---
ExecutionFrequency: rate(1 minute)
LambdaHandlerFunction: autospotting
LambdaMemorySize: '1024'
LambdaS3Bucket: cloudprowess
LambdaZipPath: nightly/lambda.zip
MinOnDemandNumber: '1'
SpotProductDescription: Linux/UNIX (Amazon VPC)
TagFilteringMode: opt-out
